import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: " Admin:This is admin page",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
      <>
      {children}
      Admin layout
      </>
  );
}
