import React from 'react'

const about = () => {
  return (
    <div>
      Hey i am About page
    </div>
  )
}

export default about
export const metadata = {
    title: "It is About page",
    description: "Generated by create next app",
  };